trigger:
- master

jobs:
- job: 'Windows'

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6' 
        addToPath: true 
        architecture: 'x86'

  - script: python --version
